name: WALKBOT
favicon: null
layout_spectrum: 0.73251
typography_spectrum: 0.61342
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#ebebeb'
    - '#d2d2d2'
    - '#c3c3c3'
    - '#b3b3b3'
  brandStrength: 0.6450486539397389
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
