name: WALKBOT
favicon: null
layout_spectrum: 0.66176
typography_spectrum: 0.50163
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#ebebeb'
    - '#d2d2d2'
    - '#c3c3c3'
    - '#b3b3b3'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
