name: walkbot.pl
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7949
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c8c8c8'
    - '#272727'
    - '#5b5b5b'
    - '#ec5f5f'
  brandStrength: 0.6450486539397389
  lightness: 0.09831219539046288
  saturation: 0.4745217349845916
  rhythmicContrast: 0.5833785152062774
purpose: []
