name: WALKBOT
favicon: null
layout_spectrum: 0.3988326962571591
typography_spectrum: 0.7444479153491557
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-10107709-8
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.4675092070829123
  lightness: 0.20780215738341212
  saturation: 0.6578535470180213
  rhythmicContrast: 0.13184548332355917
purpose: []
